### ISSUE TITLE
Add simple example with DevIL

### ISSUE THREAD

**Issue by tranek** [panzi/VTFLib#2]
It is mentioned here http://panzi.github.io/VTFLib/index.html that VTFLib works with DevIL. Is it possible that you could please add that example or make another one and add it to the VTFLib repository as an example on how to use VTFLib? Maybe even add it to the repository wiki if not included as an actual source file?

Something like extending the DevIL `simple.c` example with the VTFLib to read in .vtf files and export them to something simple like .png or .tga would be fantastic.

Thank you!

**Comment by klausenbusk** [comment]
DevIL has supported VTF since 1.7.5 (released in December 2008) it seems, and it seems to work.
I'm not sure how it handle animated VTF through.
`ilur -l foo.vtf -s bar.tga`

Just in case someone else stumble on this issue..
